### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by basv1996** [MelvinIdema/frontend-applications#2]
Je readMe heeft nog de boiler plate van React. Het zou leuk zijn om hier een goede beschrijving neer te zetten van je applicatie. Bijvoorbeeld wat je applicatie doet, hoe deze eruit ziet, hoe ik de applicatie zelf kan downloaden en gebruiken.

**Comment by MelvinIdema** [comment]
Thanks Bas, is opgelost 👍🏼
